### ISSUE TITLE
v1下的author.js authorApi.post去掉了new Auth().m后用postman post失败，显示error

### ISSUE THREAD

**Issue by tomixiaohei** [smileShirmy/smile-blog-koa#4]
v1下的author.js authorApi.post去掉了new Auth().m后用postman post失败，显示error
![image](https://user-images.githubusercontent.com/24702137/69780246-a6181300-11e5-11ea-9039-ce1e92cd8b8c.png)

**Comment by tomixiaohei** [comment]
![image](https://user-images.githubusercontent.com/24702137/69787264-15e2c980-11f7-11ea-91c8-9df0346a42e1.png)

**Comment by smileShirmy** [comment]
这个项目已经不维护了，这边推荐你使用[lin-cms-koa](https://github.com/TaleLin/lin-cms-koa)，这是一套更高效的内容管理系统框架，也有[lin-cms-vue](https://github.com/TaleLin/lin-cms-vue)配合使用。
